// Use this file to store frequently used types and interfaces and import them into components as needed. 
// Types for specific component Props should still be defined in the component file itself.

export interface epcCertificateObject extends Object {
    low_energy_fixed_light_count: number;
    address: string;
    uprn_source: string;
    floor_height: number;
    heating_cost_potential: number;
    unheated_corridor_length: number;
    hot_water_cost_potential: number;
    construction_age_band: string;
    potential_energy_rating: string;
    mainheat_energy_eff: string;
    windows_env_eff: string;
    lighting_energy_eff: string;
    environment_impact_potential: number;
    glazed_type: string;
    heating_cost_current: number;
    address3: string;
    mainheatcont_description: string;
    sheating_energy_eff: string;
    property_type: string;
    local_authority_label: string;
    fixed_lighting_outlets_count: number;
    energy_tariff: string;
    mechanical_ventilation: string;
    hot_water_cost_current: number;
    county: string;
    postcode: string;
    solar_water_heating_flag: string;
    constituency: string;
    co2_emissions_potential: number;
    number_heated_rooms: number;
    floor_description: string;
    energy_consumption_potential: number;
    local_authority: string;
    built_form: string;
    number_open_fireplaces: number;
    windows_description: string;
    glazed_area: string;
    inspection_date: Date;
    mains_gas_flag: string;
    co2_emiss_curr_per_floor_area: number;
    address1: string;
    heat_loss_corridor: string;
    flat_storey_count: string;
    constituency_label: string;
    roof_energy_eff: string;
    total_floor_area: number;
    building_reference_number: string;
    environment_impact_current: number;
    co2_emissions_current: number;
    roof_description: string;
    floor_energy_eff: string;
    number_habitable_rooms: number;
    address2: string;
    hot_water_env_eff: string;
    posttown: string;
    mainheatc_energy_eff: string;
    main_fuel: string;
    lighting_env_eff: string;
    windows_energy_eff: string;
    floor_env_eff: string;
    lighting_description: string;
    roof_env_eff: string;
    walls_energy_eff: string;
    photo_supply: string;
    lighting_cost_potential: number;
    mainheat_env_eff: string;
    multi_glaze_proportion: number;
    main_heating_controls: number;
    lodgement_datetime: Date;
    flat_top_storey: string;
    current_energy_rating: string;
    secondheat_description: number;
    walls_env_eff: string;
    transaction_type: string;
    uprn: string;
    current_energy_efficiency: number;
    energy_consumption_current: number;
    mainheat_description: string;
    lighting_cost_current: number;
    lodgement_date: Date;
    extension_count: number;
    mainheatc_env_eff: string;
    lmk_key: string;
    wind_turbine_count: number;
    tenure: string;
    floor_level: string;
    potential_energy_efficiency: number;
    hot_water_energy_eff: string;
    low_energy_lighting: number;
    walls_description: string;
    hotwater_description: string;
  };

  export interface epcAnalyticsObject {
    mean_current_energy_efficiency: number;
    mean_current_environment_impact : number;
    mean_current_energy_consumption : number;
    mean_current_co2_consumption : number;
    mean_current_lighting_cost : number;
    mean_current_heating_cost : number;
    mean_current_hot_water_cost : number;
    mean_potential_energy_efficiency : number;
    mean_potential_environment_impact : number;
    mean_potential_energy_consumption : number;
    mean_potential_co2_consumption : number;
    mean_potential_lighting_cost : number;
    mean_potential_heating_cost : number;
    mean_potential_hot_water_cost : number;
    normalised_current_energy_efficiency : Array<number>;
    normalised_current_environment_impact : Array<number>;
    normalised_current_energy_consumption : Array<number>;
    normalised_current_co2_consumption : Array<number>;
    normalised_current_lighting_cost : Array<number>;
    normalised_current_heating_cost : Array<number>;
    normalised_current_hot_water_cost : Array<number>;
  }

  export interface epcRecommendationObject {
    lmk_key: string;
    improvement_item: number;
    indicative_cost : string;
    improvement_summary_text : string;
    improvement_descr_text : string;
    improvement_id : string;
    improvement_id_text : string;
  }