// Use this file to store frequently used types and interfaces and import them into components as needed. 
// Types for specific component Props should still be defined in the component file itself.

export interface epcCertificateObject extends Object {
    lowEnergyFixedLightCount: number;
    address: string;
    uprnSource: string;
    floorHeight: number;
    heatingCostPotential: number;
    unheatedCorridorLength: number;
    hotWaterCostPotential: number;
    constructionAgeBand: string;
    potentialEnergyRating: string;
    mainheatEnergyEff: string;
    windowsEnvEff: string;
    lightingEnergyEff: string;
    environmentImpactPotential: number;
    glazedType: string;
    heatingCostCurrent: number;
    address3: string;
    mainheatcontDescription: string;
    sheatingEnergyEff: string;
    propertyType: string;
    localAuthorityLabel: string;
    fixedLightingOutletsCount: number;
    energyTariff: string;
    mechanicalVentilation: string;
    hotWaterCostCurrent: number;
    county: string;
    postcode: string;
    solarWaterHeatingFlag: string;
    constituency: string;
    co2EmissionsPotential: number;
    numberHeatedRooms: number;
    floorDescription: string;
    energyConsumptionPotential: number;
    localAuthority: string;
    builtForm: string;
    numberOpenFireplaces: number;
    windowsDescription: string;
    glazedArea: string;
    inspectionDate: Date;
    mainsGasFlag: string;
    co2EmissCurrPerFloorArea: number;
    address1: string;
    heatLossCorridor: string;
    flatStoreyCount: string;
    constituencyLabel: string;
    roofEnergyEff: string;
    totalFloorArea: number;
    buildingReferenceNumber: string;
    environmentImpactCurrent: number;
    co2EmissionsCurrent: number;
    roofDescription: string;
    floorEnergyEff: string;
    numberHabitableRooms: number;
    address2: string;
    hotWaterEnvEff: string;
    posttown: string;
    mainheatcEnergyEff: string;
    mainFuel: string;
    lightingEnvEff: string;
    windowsEnergyEff: string;
    floorEnvEff: string;
    lightingDescription: string;
    roofEnvEff: string;
    wallsEnergyEff: string;
    photoSupply: string;
    lightingCostPotential: number;
    mainheatEnvEff: string;
    multiGlazeProportion: number;
    mainHeatingControls: number;
    lodgementDatetime: Date;
    flatTopStorey: string;
    currentEnergyRating: string;
    secondheatDescription: number;
    wallsEnvEff: string;
    transactionType: string;
    uprn: string;
    currentEnergyEfficiency: number;
    energyConsumptionCurrent: number;
    mainheatDescription: string;
    lightingCostCurrent: number;
    lodgementDate: Date;
    extensionCount: number;
    mainheatcEnvEff: string;
    lmkKey: string;
    windTurbineCount: number;
    tenure: string;
    floorLevel: string;
    potentialEnergyEfficiency: number;
    hotWaterEnergyEff: string;
    lowEnergyLighting: number;
    wallsDescription: string;
    hotwaterDescription: string;
  };

  export interface epcAnalyticsObject {
    meanCurrentEnergyEfficiency: number;
    meanCurrentEnvironmentImpact : number;
    meanCurrentEnergyConsumption : number;
    meanCurrentCo2Consumption : number;
    meanCurrentLightingCost : number;
    meanCurrentHeatingCost : number;
    meanCurrentHotWaterCost : number;
    meanPotentialEnergyEfficiency : number;
    meanPotentialEnvironmentImpact : number;
    meanPotentialEnergyConsumption : number;
    meanPotentialCo2Consumption : number;
    meanPotentialLightingCost : number;
    meanPotentialHeatingCost : number;
    meanPotentialHotWaterCost : number;
    normalisedCurrentEnergyEfficiency : Array<number>;
    normalisedCurrentEnvironmentImpact : Array<number>;
    normalisedCurrentEnergyConsumption : Array<number>;
    normalisedCurrentCo2Consumption : Array<number>;
    normalisedCurrentLightingCost : Array<number>;
    normalisedCurrentHeatingCost : Array<number>;
    normalisedCurrentHotWaterCost : Array<number>;
  }

  export interface epcRecommendationObject {
    lmkKey: string;
    improvementItem: number;
    indicativeCost : string;
    improvementSummaryText : string;
    improvementDescrText : string;
    improvementId : string;
    improvementIdText : string;
  }