# Generated by Django 4.0.1 on 2022-02-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmk_key', models.CharField(max_length=200)),
                ('improvement_id', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('was_effective', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Completed Recommendation',
            },
        ),
    ]
