# Generated by Django 4.0.1 on 2022-02-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_recommendation_completedrecommendation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completedrecommendation",
            name="was_effective",
        ),
    ]
