# Generated by Django 4.0.1 on 2022-03-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_completedrecommendation_was_effective'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedrecommendation',
            name='postcode',
            field=models.CharField(default='', max_length=16),
        ),
    ]
