# Generated by Django 4.0.1 on 2022-03-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_completedrecommendation_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedrecommendation',
            name='postcode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
